services:
  db:
    image: postgres:16
    container_name: school_db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: school_backend
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:
